--- 
- name: Frontend Install 
  hosts: all 
  tasks:
  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
  - name: nginx configuration 
    ansible.builtin.copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
