- name: Frontend Install 
  hosts: all
  become: true 
  tasks:
  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed
  - name: nginx configuration 
    ansible.builtin.copy:
      src: files/nginx.conf
      dest: /etc/nginx/nginx.conf
   
    
