---
# Java role - Java applications setup

- name: Install Java packages
  dnf:
    name: "{{ java_packages }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Verify Java installation
  command: java -version
  register: java_version
  changed_when: false

- name: Display Java version
  debug:
    msg: "Java version: {{ java_version.stderr }}"

- name: Create Java application directory
  file:
    path: "{{ app_home }}/shipping"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'

- name: Download shipping application artifacts
  get_url:
    url: "{{ app_artifacts_url }}/shipping-{{ app_version }}.zip"
    dest: /tmp/shipping.zip
    mode: '0644'
  when: inventory_hostname in groups['webservers']

- name: Extract shipping application
  unarchive:
    src: /tmp/shipping.zip
    dest: "{{ app_home }}/shipping"
    remote_src: yes
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
  when: inventory_hostname in groups['webservers']

- name: Build shipping application
  command: mvn clean package
  args:
    chdir: "{{ app_home }}/shipping"
  when: inventory_hostname in groups['webservers']

- name: Rename shipping JAR file
  command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: "{{ app_home }}/shipping"
  when: inventory_hostname in groups['webservers']

- name: Create shipping service file
  template:
    src: shipping.service.j2
    dest: /etc/systemd/system/shipping.service
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd

- name: Start and enable shipping service
  systemd:
    name: shipping
    state: started
    enabled: yes

- name: Display Java services status
  debug:
    msg: "Java service (shipping) is running" 